### PR TITLE
new loki realtime logging handler

### PR DESCRIPTION
**Pull request by wguanicedew**

### CODE REVIEW

**Comment by PalNilsson** [comment]
Thanks Wen. But can you please add function documentation including type hints? Also, please run pylint on the code and make sure you get a score around 9. This will soon all be requirements.

**Comment by wguanicedew** [comment]
I updated the codes. Now pylint score is 9.25.

**Comment by PalNilsson** [comment]
Great. Can you add the type hints as well please?

**Comment by wguanicedew** [comment]
Added type hints

**Comment by PalNilsson** [comment]
Sorry Wen, one more change - the requests module is not a standard Python module, can you please put a try-statement around it (the import + the single usage)?

**Comment by wguanicedew** [comment]
updated to catch exceptions during importing requests.

**Comment by PalNilsson** [comment]
Thanks

**Pull request merged**
